ok

diff --git a/flacman b/flacman
--- a/flacman
+++ b/flacman
@@ -35,9 +35,9 @@ then
 
 echo
 # ################ COMMAND ################
-        ( man $1 | nl | grep -A 1 "\-$2" ) || clear && echo "NO FLAC IS FOUND." 
+        ( man $1 | nl | grep -A 1 "\-$2") || ( clear && echo "FLAC NOT FOUNDED." ) 
 #
-echo
+
 echo
 
 fi
